// Code generated by goctl. DO NOT EDIT!
// Source: message.proto

package server

import (
	"context"

	"github.com/leaper-one/2SOMEone/2someone/message/rpc/internal/logic"
	"github.com/leaper-one/2SOMEone/2someone/message/rpc/internal/svc"
	"github.com/leaper-one/2SOMEone/2someone/message/rpc/types/message"
)

type MessageServiceServer struct {
	svcCtx *svc.ServiceContext
	message.UnimplementedMessageServiceServer
}

func NewMessageServiceServer(svcCtx *svc.ServiceContext) *MessageServiceServer {
	return &MessageServiceServer{
		svcCtx: svcCtx,
	}
}

//  向手机号发送验证码
func (s *MessageServiceServer) SentMessageCode(ctx context.Context, in *message.SentMessageCodeRequest) (*message.SentMessageCodeResponse, error) {
	l := logic.NewSentMessageCodeLogic(ctx, s.svcCtx)
	return l.SentMessageCode(in)
}

//  校验验证码
func (s *MessageServiceServer) CheckMessageCode(ctx context.Context, in *message.CheckMessageCodeRequest) (*message.CheckMessageCodeResponse, error) {
	l := logic.NewCheckMessageCodeLogic(ctx, s.svcCtx)
	return l.CheckMessageCode(in)
}
