// Code generated by goctl. DO NOT EDIT!
// Source: message.proto

package message

import (
	"context"

	"github.com/leaper-one/2SOMEone/2someone/message/rpc/message/types/message"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CheckMessageCodeRequest  = message.CheckMessageCodeRequest
	CheckMessageCodeResponse = message.CheckMessageCodeResponse
	SentMessageCodeRequest   = message.SentMessageCodeRequest
	SentMessageCodeResponse  = message.SentMessageCodeResponse

	Message interface {
		//  向手机号发送验证码
		SentMessageCode(ctx context.Context, in *SentMessageCodeRequest, opts ...grpc.CallOption) (*SentMessageCodeResponse, error)
		//  校验验证码
		CheckMessageCode(ctx context.Context, in *CheckMessageCodeRequest, opts ...grpc.CallOption) (*CheckMessageCodeResponse, error)
	}

	defaultMessage struct {
		cli zrpc.Client
	}
)

func NewMessage(cli zrpc.Client) Message {
	return &defaultMessage{
		cli: cli,
	}
}

//  向手机号发送验证码
func (m *defaultMessage) SentMessageCode(ctx context.Context, in *SentMessageCodeRequest, opts ...grpc.CallOption) (*SentMessageCodeResponse, error) {
	client := message.NewMessageClient(m.cli.Conn())
	return client.SentMessageCode(ctx, in, opts...)
}

//  校验验证码
func (m *defaultMessage) CheckMessageCode(ctx context.Context, in *CheckMessageCodeRequest, opts ...grpc.CallOption) (*CheckMessageCodeResponse, error) {
	client := message.NewMessageClient(m.cli.Conn())
	return client.CheckMessageCode(ctx, in, opts...)
}
