// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	accounts "github.com/leaper-one/2SOMEone/2someone/user/api/internal/handler/accounts"
	"github.com/leaper-one/2SOMEone/2someone/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/sent-phone-code/:phone",
				Handler: accounts.SentPhoneCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/signup",
				Handler: accounts.SignUpHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/signin",
				Handler: accounts.SignInHandler(serverCtx),
			},
		},
		rest.WithPrefix("/user/v1"),
	)
}
