// Code generated by goctl. DO NOT EDIT.
package types

type SentPhoneCodeReq struct {
	Phone string `path:"phone"`
}

type SentPhoneCodeResp struct {
	Code   int32  `json:"code"`
	Msg    string `json:"msg"`
	Msg_id uint64 `json:"msg_id"`
}

type SignUpReq struct {
	Phone      string `json:"phone"`
	Phone_code string `json:"phone_code"`
	Password   string `json:"password"`
	Msg_id     uint64 `json:"msg_id"`
}

type SignUpResp struct {
	Code    int32  `json:"code"`
	Msg     string `json:"msg"`
	User_id int64  `json:"user_id"`
	Token   string `json:"token"`
}

type SignInReq struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type SignInResp struct {
	Code  int32  `json:"code"`
	Msg   string `json:"msg"`
	Token string `json:"token"`
}

type GetuseridReq struct {
	Buid uint64 `json:"buid, optional"`
}

type GetuseridResp struct {
	Code    int32  `json:"code"`
	Msg     string `json:"msg"`
	User_id string `json:"user_id"`
}

type MeResp struct {
	Code   int32  `json:"code"`
	Msg    string `json:"msg"`
	UserId string `json:"user_id"`
	Name   string `json:"name"`
	Avatar string `json:"avatar"`
	Buid   int64  `json:"buid"`
	Email  string `json:"email"`
	Phone  string `json:"phone"`
}

type SetInfoReq struct {
	Name   string `json:"name"`
	Avatar string `json:"avatar"`
	Buid   string `json:"buid"`
}

type SetInfoResp struct {
	Code int32  `json:"code"`
	Msg  string `json:"msg"`
}

type GetUserIdByBuidReq struct {
	Buid int64 `json:"buid"`
}

type GetUserIdByBuidResp struct {
	Code   int32  `json:"code"`
	Msg    string `json:"msg"`
	UserId string `json:"user_id"`
}
