name: build 2someone dev

on:
  push:
    branches: [ dev ]
    paths-ignore:
      # - .github/workflows/dev_docker_build.yml
      - .github/workflows/master_docker_build.yml
      - .github/workflows/deploy_2someone_release.yml
      - README.md
  pull_request:
    branches: [ dev ]

jobs:

  build-message-rpc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: registry.cn-shanghai.aliyuncs.com
          repository: leaperone/2someone
          file: rpc/message-rpc/Dockerfile
          tags: message-rpc-v1-dev
          
  build-user-rpc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: registry.cn-shanghai.aliyuncs.com
          repository: leaperone/2someone
          file: rpc/user-rpc/Dockerfile
          tags: user-rpc-v1-dev

  build-user-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: registry.cn-shanghai.aliyuncs.com
          repository: leaperone/2someone
          file: api/user-api/Dockerfile
          tags: user-api-v1-dev
