name: build 2someone latest

on:
  push:
    branches: [ master ]
    paths-ignore:
      - .github/workflows/dev_docker_build.yml
      - .github/workflows/master_docker_build.yml
      - .github/workflows/deploy_2someone_release.yml
      - README.md
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: registry.cn-shanghai.aliyuncs.com
          repository: leaperone/2someone
          tags: latest